%YAML 1.2
---
sources:
  # Class
  - { id: B0D1973, tit: Баян. Підготовча група,
      aut: [О. Денисов], pub: Музична Україна, yr: 1973 }
  - { id: B0DU1982, tit: Баян. Підготовча група,
      aut: [О. Денисов, В. Угринович], pub: Музична Україна, yr: 1982 }
  - { id: B1AK1979, tit: Баян. 1 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1979 }
  - { id: B1AK1985, tit: Баян. 1 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1985 }
  - { id: B2AK1979, tit: Баян. 2 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1979 }
  - { id: B2AK1987, tit: Баян. 2 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1987 }
  # Tutorial
  - { id: BTBC1936, tit: Самоучитель игры на баяне,
      aut: [А. Басурманов, Н. Чайкин], pub: Советский композитор, yr: 1936 }
  - { id: BTB1978, tit: Самоучитель игры на баяне,
      aut: [А. Басурманов], pub: Советский композитор, yr: 1978 }
  # School
  # Course
  - { id: TYBCB11970, tit: Трехгодичный курс обучения игры на баяне,
      sub: Часть 1, aut: [А. Басурманов], pub: Советский композитор, yr: 1970 }
  - { id: TYBCB21971, tit: Трехгодичный курс обучения игры на баяне,
      sub: Часть 2, aut: [А. Басурманов], pub: Советский композитор, yr: 1971 }
  # Misc
