%YAML 1.2
---
sources:
  # Class
  - { id: B0D1973, tit: Баян. Підготовча група,
      aut: [О. Денисов], pub: Музична Україна, yr: 1973 }
  - { id: B0DU1982, tit: Баян. Підготовча група,
      aut: [О. Денисов, В. Угринович], pub: Музична Україна, yr: 1982 }
  - { id: B1AK1979, tit: Баян, sub: 1 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1979 }
  - { id: B1AK1985, tit: Баян, sub: 1 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1985 }
  - { id: B2AK1979, tit: Баян, sub: 2 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1979 }
  - { id: B2AK1987, tit: Баян, sub: 2 клас,
      aut: [І. Алексєєв, М. Корецький], pub: Музична Україна, yr: 1987 }
  # Tutorial
  - { id: BTBC1936, tit: Самоучитель игры на баяне,
      aut: [А. Басурманов, Н. Чайкин], pub: Советский композитор, yr: 1936 }
  - { id: BTB1978, tit: Самоучитель игры на баяне,
      aut: [А. Басурманов], pub: Советский композитор, yr: 1978 }
  # School
  # Course
  - { id: TYBC1B1970, tit: Трехгодичный курс обучения игры на баяне,
      sub: Часть 1, aut: [А. Басурманов], pub: Советский композитор, yr: 1970 }
  - { id: TYBC2B1971, tit: Трехгодичный курс обучения игры на баяне,
      sub: Часть 2, aut: [А. Басурманов], pub: Советский композитор, yr: 1971 }
  # Study
  - { id: SB1NU1979, tit: Етюди для баяна на різні види техніки, sub: 1 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, yr: 1979 }
  - { id: SB2NU1977, tit: Етюди для баяна на різні види техніки, sub: 2 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, yr: 1977 }
  - { id: SB4NU1978, tit: Етюди для баяна на різні види техніки, sub: 4 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, yr: 1978 }
  - { id: SB5NU1980, tit: Етюди для баяна на різні види техніки, sub: 5 клас,
      aut: [А. Нечипоренко, В. Угринович], pub: Музична Україна, yr: 1980 }
  # Misc
